server:
  port: 23102

spring:
  application:
    name: common
    index: 0

  datasource:
    url: jdbc:mysql://localhost:3306/efupay_common
    username: root
    password: 
    testWhileIdle: true
    validationQuery: SELECT 1

  cloud:
    stream:
      instanceCount: 1
      instanceIndex: 0
      kafka:
        binder:
          offsetUpdateTimeWindow: 10000
          #offsetUpdateCount: 0
          requiredAcks: 1
          minPartitionCount: 1
          replicationFactor: 1

        bindings:
          input:
            consumer:
              autoCommitOffset: true
              startOffset: earliest
              headerMode: raw
          output:
            producer:
              bufferSize: 16384
              sync: true
              batchTimeout: 0

      bindings:
        input:
          # destination: testq1
          group: common
          consumer:
            concurrency: 1
            partitioned: false
            headerMode: raw
        output:
          # destination: testq2
          group: common
          producer:
            # partitionKeyExpression: null
            # partitionKeyExtractorClass: null
            # partitionSelectorExpression: null
            # partitionSelectorClass: null
            partitionCount: 1
            headerMode: raw

